# Generated by Django 4.1.1 on 2022-09-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medservices.hospital')),
            ],
        ),
    ]
