# Generated by Django 4.1.1 on 2022-09-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_timeslots',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medservices.doctor'),
        ),
    ]
