# Generated by Django 4.1 on 2022-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medservices', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('pat_name', models.CharField(max_length=200)),
                ('pat_address', models.CharField(max_length=200)),
                ('pat_contact', models.IntegerField()),
                ('paid_amount', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('not paid', 'not paid')], max_length=20)),
            ],
        ),
    ]
