# Generated by Django 4.0.5 on 2022-09-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medservices', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='h_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medservices.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='speciality',
            field=models.CharField(choices=[('ear', 'ear'), ('eye', 'eye'), ('cardiology', 'cardiology')], max_length=50),
        ),
    ]
