# Generated by Django 4.1.1 on 2022-09-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medservices', '0003_alter_blood_bank_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_bank',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
