# Generated by Django 2.2.7 on 2022-09-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medservices', '0004_delete_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
