# Generated by Django 4.0.5 on 2022-09-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medservices', '0004_rename_date_appointment_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
    ]
