# Generated by Django 4.1.1 on 2022-09-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medservices', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total_amount',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
